apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: adm
spec:
  acme:
    # The ACME server URL
    # The production API is used for the ClusterIssuer
    # server: https://acme-v02.api.letsencrypt.org/directory
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "maxim@kyc-chain.com"
    # name is used for storing the ACME account key.
    # the secret will be created by cert-manager after ACME registration
    privateKeySecretRef:
      name: letsencrypt-production
  ns01:
      providers:
      - name: google-clouddns
        clouddns:
          serviceAccountSecretRef:
            name: external-dns
            key: credentials.json