apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: adm
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 0.15.2
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: letsencrypt-production
      defaultIssuerKind: ClusterIssuer
      defaultACMEChallengeType: dns01
      defaultACMEDNS01ChallengeProvider: google-clouddns
    extraArgs:
      - '--dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53'
    
