apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: adm
spec:
  releaseName: external-dns
  chart:
    repository: https://charts.bitnami.com/bitnami
    name: external-dns
    version: 3.2.3
  values:
    provider: google
    google:
      serviceAccountSecret: external-dns
    policy: sync
    registry: txt
    txtOwnerId: k8s-cluster
    rbac:
      create: true
    domainFilters:
      - gc.selfkey.org
    sources:
      - ingress
    
