---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selfkey-web-stage
  namespace: stage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:dev-*
spec:
  releaseName: selfkey-web-stage
  chart:
    git: git@github.com:SelfKeyFoundation/selfkey-web
    path: charts/selfkey-web
    ref: dev
  values:
    image: asia.gcr.io/selfkey2/selfkey-web@sha256:1f59131fc6f1c96be72cb2bcc6cb6d761a336e18ff383568f7224b48eac61cbc
    replicaCount: 1
    ingressDomain: stage-selfkey-web.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 0.5
        memory: 0.2Gi
      requests:
        cpu: 0.2
        memory: 0.1Gi
