apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lockdao-service-staging
  namespace: stage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: "semver:*"
spec:
  releaseName: lockdao-service-staging
  chart:
    git: git@github.com:SelfKeyFoundation/lockdao-service
    path: charts/lockdao-service-staging
    ref: staging
  values:
    image: asia.gcr.io/selfkey2/lockdao-service-staging
    replicaCount: 1
    ingressDomain: lockdao-staging.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 1
        memory: 4Gi
      persistence:
        size: 8Gi
