apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selfkey-issuer-stage
  namespace: stage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: "semver:*"
spec:
  releaseName: selfkey-issuer-stage
  chart:
    git: git@github.com:SelfKeyFoundation/selfkey-issuer-service
    path: charts/selfkey-issuer
    ref: dev
  values:
    image: asia.gcr.io/selfkey2/selfkey-issuer-service:v1.0.2
    replicaCount: 1
    ingressDomain: stage-issuer.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 0.5
        memory: 0.2Gi
      requests:
        cpu: 0.2
        memory: 0.1Gi
      persistence:
        size: 8Gi
