---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selfkey-api-stage
  namespace: stage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:dev-*
spec:
  releaseName: selfkey-api-stage
  chart:
    git: git@github.com:SelfKeyFoundation/selfkey-api
    path: charts/selfkey-api
    ref: dev
  values:
    image: asia.gcr.io/selfkey2/selfkey-api:dev-5ca88c784ea066a24d1774748585617f131f123d
    replicaCount: 1
    ingressDomain: stage-api.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 0.5
        memory: 0.2Gi
      requests:
        cpu: 0.2
        memory: 0.1Gi
    mongodb:
      enabled: true
      clusterDomain: cluster.local
      architecture: replicaset
      auth:
        enabled: true
        username: selfkey
        database: selfkey-api
        existingSecret: sk-api-mongo
      persistence:
        size: 8Gi
