apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selfkey-id-service-staging
  namespace: stage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:staging-*
spec:
  releaseName: selfkey-id-service-staging
  chart:
    git: git@github.com:SelfKeyFoundation/selfkey-id-service
    path: charts/selfkey-id-service-staging
    ref: staging
  values:
    image: asia.gcr.io/selfkey2/selfkey-id-service-staging
    replicaCount: 1
    ingressDomain: selfkey-id-service-staging.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 1
        memory: 4Gi
      persistence:
        size: 8Gi
