apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sk-api-mongo
  namespace: stage
spec:
  encryptedData:
    mongodb-password: AgCp3ql+f9ckSuEEe4pmfeaEjPWCHI7hElTYXBOA2ZP3ix7rWPIXCyxK/89PeNFyivE+9TCyckl3swwd5bwbYji+gHTo1UKXXPjxuMeyjHZQYgZwaQVV/M+sTfOvEri2d68DmWg5eOR1hlzG8mNPKsQgS8toUJcnJCqA5s87WQLwrnAxnwrRNkYH23AeqhUPsIajJatRy+4yTtbdK285SyyF5le5ugQ8FyHc7v14IHQ884PONhV0Q+g5uVuVFLJ51QXh+1SqIe9GL0ei9Uk6eaT3SuoO6jSFPJDq0XfC3Kw3a1hFez6Q0+XEdOP+f/J6KLEu1ccNrWAhhHpew+pUEaS7dFiUP4BPt9RGcpGYdWEPz9/js1ajxIH03L8AhYYl2uNNm0VQNYg5COQUj1MKdj0BCyLL6H3OO7C/4iaHu2HbiJIoPFL6WTwpfA9oxZPGFzft+b7nzqxfkc3GpIHl9FXgRrtKBGIwlHIbll5LE3kltqnJ4sehBdrd947zfG9F74quocw3dt/YmdLb79O81mcneIQ902zGoOJdoZa5BoodegoBnT9hLmsmgVdf5fDp+RVa0dEt3i4Qoi8lyw5lYmDBBAylUUaMDTAZwUDyDfeQyrHcHZ9NGsH8kmbmR2T2MbVRqPZG4RY14PeIUsrZuEjhULW4MaUH+uBY3YtyvZCeivTiji09Xs2EHcMyL9i3Pt2zvuqvVeEBaNRj3ng9HKGNREZtDg==
    mongodb-root-password: AgB98TVM9YTA+UWBPU5rDW4YTVdczbUDgI5nRXOhA8g6ut2K2TFqKY0kmq6fFn/VlZjWXrwrRNOy+kj6D0eHGsjTrBgXLCt3e+Wgz07ivYh6RqzItRSoq0Qxc9I/wJTsrCUiC9DfeQZAS842mocrQEEyc4cgVBbckYB+Db0gXl1j/i8cT1xfp4NRXJh93mHp78DPaubfdXwfMv+DTrJV7ud2+pkl0DXvBx9oVks72pR0E9P+8jirx5ElUJwgxzh1c4DrBg6uxtjQDupd+cNMqWArxt92XiROlXFCiorCqiokMbNTXu4WjBD8++9P2337A+ZJsFAnPTTDW/NOJxmUd/3Zkc8ZMZ3VwjF2L5Vq53xy0X5vXSSiTASBtDbH71gmIVGmlIJOgRpQGda0KG3U5/T04HdOQBgTMcyEly4oMI2vj2guUNoEOc6Hv7xAHDh/bpo+S8iba8hdrzzh8XWEQ9pgTRbuIHVrCweLMZlsTpRp4rfheIOYa7flmySWrbwaUb+6H0H7xjBk30v7FXzcwJF0SYzNY+hDEUNsqk2yP2K0h2Bf3hcQ1wNjc/82uYN9ufVdyhEluqjUp9/XtPJbHA+VrFBUkX13j0BQt4ZtumxGvTIpeCWXY8SM4/qwZVM6qEIi0JKkETuQALbZNQKBfJTXobyWhdbR8OaWzeHj4Qyi66bquPceaFUBge60WZg+T6vMNTwO/4AEsWrvuzS21HQUAsrq+Q==
  template:
    metadata:
      creationTimestamp: null
      name: sk-api-mongo
      namespace: stage

