---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: matomo
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:4.*.*-apache
spec:
  releaseName: matomo
  chart:
    git: git@github.com:SelfKeyFoundation/matomo
    path: charts/matomo
    ref: master
  values:
    image:
      repository: matomo
      tag: '4.2.1-apache'
    replicaCount: 2
    matomo:
      proxyUri: 'yes'
    db:
      port: '3306'
      host: '127.0.0.1'
    dbProxy:
      instances: "-instances=selfkey2:asia-east2:matomo=tcp:3306"
    gcePersistentDisk:
      pdName: matomo-nfs-disk
      fsType: ext4
      size: 20Gi
    dbServiceAccount: matomo-sql
    ingressDomain: matomo.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    websiteUrl: 'https://analytics.selfkey.org'
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0.5
        memory: 0.5Gi
