apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selfkey-lockdao
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: "semver:*"
spec:
  releaseName:selfkey-lockdao
  chart:
    git: git@github.com:SelfKeyFoundation/poi-service
    path: charts/lockdao
    ref: master
  values:
    image: asia.gcr.io/selfkey2/selfkey-lockdao-service
    replicaCount: 1
    ingressDomain: lockdao.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 1
        memory: 4Gi
      persistence:
        size: 8Gi
