---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selfkey-api-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:master-*
spec:
  releaseName: selfkey-api-prod
  chart:
    git: git@github.com:SelfKeyFoundation/selfkey-api
    path: charts/selfkey-api
    ref: master
  values:
    image: asia.gcr.io/selfkey2/selfkey-api:master-6c3ee89817b900e866a60080b4636491b9ab2fef
    replicaCount: 1
    ingressDomain: api.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 0.5
        memory: 0.2Gi
      requests:
        cpu: 0.2
        memory: 0.1Gi