---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: selfkey-webmp-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:master-*
spec:
  releaseName: selfkey-webmp-prod
  chart:
    git: git@github.com:SelfKeyFoundation/web-marketplaces
    path: charts/web-marketplaces
    ref: master
  values:
    image: asia.gcr.io/selfkey2/web-marketplaces:prod-f76e8cc5d8bd634cece8e28bff5fda8013776080
    replicaCount: 1
    ingressDomain: webmp.gc.selfkey.org
    tlsSecret: org-selfkey-gc-wc
    # ingressHttpDisable: true
    resources:
      limits:
        cpu: 0.5
        memory: 0.2Gi
      requests:
        cpu: 0.2
        memory: 0.1Gi
